version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - '.:/usr/src/app'
    working_dir: /usr/src/app
    ports:
      - '5000:5000'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    restart: unless-stopped
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
